<script setup lang="ts">
import {Head,Link,useForm} from '@inertiajs/vue3';import {ref,onMounted} from 'vue';import QRCode from 'qrcode';import Shell from '../Layouts/Shell.vue';import AttachmentUpload from '../Components/AttachmentUpload.vue';
const props=defineProps<{equipment:{id:number;name:string;zone:string|null;workstation_number:string|null;cpu:string|null;gpu:string|null;ram_mb:number|null;disks:string|null;serial_number:string|null;inventory_number:string|null;ip:string|null;mac:string|null;status:string;club:{name:string};last_inspection_date:string|null;next_inspection_date:string|null};attachments:{id:number;name:string}[];tickets:{data:{id:number;description:string;status:string}[];total:number;next_page_url:string|null;prev_page_url:string|null};canEdit:boolean}>();
const e=props.equipment;const form=useForm({name:e.name,zone:e.zone??'',workstation_number:e.workstation_number??'',cpu:e.cpu??'',gpu:e.gpu??'',ram_mb:e.ram_mb,disks:e.disks??'',serial_number:e.serial_number??'',inventory_number:e.inventory_number??'',ip:e.ip??'',mac:e.mac??'',status:e.status});
const fields={name:'Название',zone:'Зона',workstation_number:'Номер места',cpu:'CPU',gpu:'GPU',ram_mb:'RAM, МБ',disks:'Накопители',serial_number:'Серийный номер',inventory_number:'Инвентарный номер',ip:'IP',mac:'MAC'};
const qr=ref('');onMounted(async()=>{qr.value=await QRCode.toDataURL(window.location.origin+'/equipment/'+e.id);});
</script>
<template><Head :title="equipment.name"/><Shell><div class="heading"><div><p class="eyebrow">{{equipment.club.name}} · ID {{equipment.id}}</p><h1>{{equipment.name}}</h1></div><img v-if="qr" :src="qr" alt="QR карточки оборудования, требуется вход" width="110" height="110"/></div><p>Последний осмотр: {{equipment.last_inspection_date||'не выполнен'}} · Следующий: {{equipment.next_inspection_date||'не назначен'}}</p>
<form class="panel form-grid" @submit.prevent="form.post('/equipment/'+equipment.id)"><label v-for="(title,key) in fields" :key="key">{{title}}<input v-model="form[key as keyof typeof fields]" :disabled="!canEdit"/></label><label>Статус<select v-model="form.status" :disabled="!canEdit"><option value="active">Активно</option><option value="maintenance">Обслуживание</option><option value="retired">Выведено</option></select></label><button v-if="canEdit" :disabled="form.processing">Сохранить карточку</button><p class="error" v-for="error in form.errors" :key="error">{{error}}</p></form>
<section class="panel"><h2>Фотографии и документы</h2><AttachmentUpload v-if="canEdit" type="equipment" :id="equipment.id"/><p v-for="a in attachments" :key="a.id"><a :href="'/attachments/'+a.id">{{a.name}}</a></p></section><section class="panel"><h2>История неисправностей</h2><p v-if="!tickets.data.length">Заявок по устройству пока нет.</p><p v-for="t in tickets.data" :key="t.id"><Link :href="'/tickets/'+t.id">#{{t.id}} · {{t.description}}</Link> · {{({new:'Новая',accepted:'Принята',working:'В работе',approval:'Согласование',parts:'Ожидает запчастей',resolved:'Решена',closed:'Закрыта'} as Record<string,string>)[t.status]||t.status}}</p><div class="pagination"><Link v-if="tickets.prev_page_url" :href="tickets.prev_page_url">Назад</Link><Link v-if="tickets.next_page_url" :href="tickets.next_page_url">Далее</Link></div></section></Shell></template>
