<script setup lang="ts">
import { Head, Link, useForm } from '@inertiajs/vue3';import Shell from '../Layouts/Shell.vue';
defineProps<{clubs:{id:number;name:string}[];channels:{id:number;name:string;chat_id:string;enabled:boolean}[];kinds:string[];transport:string;deliveries:{data:{id:number;status:string;attempts:number;sent_at:string|null}[];next_page_url:string|null;prev_page_url:string|null};attempts:{id:number;delivery_id:number;outcome:string;http_status:number|null}[]}>();
const form=useForm({club_id:'',name:'',bot_token:'',chat_id:'',kinds:['test']});
</script>
<template><Head title="Telegram и интеграции"/><Shell><h1>Telegram и интеграции</h1><p class="success">Транспорт: {{transport==='fake'?'ТЕСТОВЫЙ — сообщения не уходят в Telegram':'Telegram API'}}</p><section class="panel"><h2>CCBoot / iCafeCloud</h2><p>Не настроено. Для подключения требуются подтверждённая документация интерфейса и ключи. Автоматическое изменение образов отсутствует.</p></section>
<form class="panel form-grid" @submit.prevent="form.post('/integrations/channels',{onSuccess:()=>form.reset('bot_token')})"><label>Клуб<select v-model="form.club_id" required><option v-for="c in clubs" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Название<input v-model="form.name" required/></label><label>Токен бота<input v-model="form.bot_token" type="password" autocomplete="off" required/></label><label>Chat ID<input v-model="form.chat_id" required/></label><fieldset><legend>Подписки</legend><label v-for="k in kinds" :key="k" class="check"><input type="checkbox" v-model="form.kinds" :value="k"/>{{k}}</label></fieldset><button :disabled="form.processing">Сохранить канал</button><p class="error" v-for="error in form.errors" :key="error">{{error}}</p></form>
<section class="panel"><h2>Каналы</h2><p v-if="!channels.length">Каналы ещё не добавлены.</p><div class="toolbar" v-for="c in channels" :key="c.id"><strong>{{c.name}} · {{c.chat_id}}</strong><Link :href="'/integrations/channels/'+c.id+'/test'" method="post" as="button">Тестовое сообщение</Link><Link :href="'/integrations/channels/'+c.id+'/toggle'" method="post" as="button">{{c.enabled?'Отключить':'Включить'}}</Link></div></section>
<section class="panel"><h2>Доставка</h2><p>При потерянном ответе Telegram повторная отправка может создать дубль. ID события помогает его распознать.</p><table><tbody><tr v-for="d in deliveries.data" :key="d.id"><td>#{{d.id}}</td><td>{{d.status}}</td><td>Попыток: {{d.attempts}}</td><td><Link v-if="d.status==='failed'" :href="'/integrations/deliveries/'+d.id+'/retry'" method="post" as="button">Повторить</Link></td></tr></tbody></table><Link v-if="deliveries.next_page_url" :href="deliveries.next_page_url">Далее</Link><Link v-if="deliveries.prev_page_url" :href="deliveries.prev_page_url">Назад</Link></section>
<section class="panel"><h2>Последние попытки</h2><p v-for="a in attempts" :key="a.id">Доставка #{{a.delivery_id}} · {{a.outcome}} · HTTP {{a.http_status??'ответ не получен'}}</p></section></Shell></template>
