<script setup lang="ts">
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';
import Shell from '../Layouts/Shell.vue';
import LivePcBoard from '../Components/LivePcBoard.vue';
defineProps<{clubs:{id:number;name:string}[];equipment:{data:{id:number;name:string;last_seen_at:string|null}[];prev_page_url:string|null;next_page_url:string|null};alerts:{id:number;equipment_id:number;metric:string;opened_at:string}[];agents:{id:string;name:string;revoked_at:string|null}[];rules:{id:number;club_id:number;metric:string;trigger_value:string;recovery_value:string;hold_seconds:number}[];agentSecret:{id:string;token:string;equipment_id:number}|null}>();
const page=usePage<{auth:{user:{role:string}}}>();const canManage=['owner','lead'].includes(page.props.auth.user.role);
const agent=useForm({club_id:'',equipment_id:'',name:''});const rule=useForm({club_id:'',metric:'cpu_load',trigger_value:85,recovery_value:75,hold_seconds:120});const maintenance=useForm({club_id:'',starts_at:'',ends_at:'',reason:''});
const confirm = (message: string) => window.confirm(message);
function signal(date:string|null){return !date?'Нет данных':Date.now()-new Date(date).getTime()>180000?'Нет свежей связи':'Связь есть';}
</script>
<template><Head title="Мониторинг"/><Shell><h1>Мониторинг</h1><p>Отсутствие heartbeat означает отсутствие свежей связи. Оно не доказывает, что ПК выключен.</p>
<div v-if="agentSecret" class="panel"><h2>Сохраните токен — он показан один раз</h2><code class="prewrap">{{JSON.stringify(agentSecret,null,2)}}</code></div>

<LivePcBoard :clubs="clubs" :can-manage="canManage"/>
<form v-if="canManage" class="panel form-grid" @submit.prevent="agent.post('/agents')"><h2>Регистрация агента для одного ПК</h2><label>Клуб<select v-model="agent.club_id" required><option v-for="c in clubs" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>ID оборудования<input type="number" v-model="agent.equipment_id" required/></label><label>Имя агента<input v-model="agent.name" required/></label><button :disabled="agent.processing">Создать регистрацию</button><p class="error" v-for="error in agent.errors" :key="error">{{error}}</p></form>
<section class="panel"><h2>Агенты</h2><p v-for="a in agents" :key="a.id">{{a.name}} · {{a.revoked_at?'Отозван':'Активен'}} <Link v-if="canManage&&!a.revoked_at" :href="'/agents/'+a.id+'/revoke'" as="button" method="post" :on-before="()=>confirm('Отозвать токен агента?')">Отозвать</Link></p></section>
<form v-if="canManage" class="panel form-grid" @submit.prevent="rule.post('/monitoring/rules')"><h2>Порог и восстановление</h2><label>Клуб<select v-model="rule.club_id" required><option v-for="c in clubs" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Метрика<select v-model="rule.metric"><option v-for="m in ['cpu_load','gpu_load','ram_used_percent','disk_free_percent']" :key="m">{{m}}</option></select></label><label>Тревога<input v-model="rule.trigger_value" type="number" required/></label><label>Восстановление<input v-model="rule.recovery_value" type="number" required/></label><label>Выдержка, секунды<input v-model="rule.hold_seconds" type="number" min="0" required/></label><button :disabled="rule.processing">Сохранить порог</button><p v-for="error in rule.errors" :key="error" class="error">{{error}}</p></form>
<section class="panel"><p v-if="!rules.length">Пороги не настроены.</p><p v-for="r in rules" :key="r.id">Клуб #{{r.club_id}} · {{r.metric}} · тревога {{r.trigger_value}} / восстановление {{r.recovery_value}} · {{r.hold_seconds}} с</p></section>
<form v-if="canManage" class="panel form-grid" @submit.prevent="maintenance.post('/monitoring/maintenance')"><h2>Техническое обслуживание</h2><label>Клуб<select v-model="maintenance.club_id" required><option v-for="c in clubs" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Начало (UTC)<input v-model="maintenance.starts_at" type="datetime-local" required/></label><label>Конец (UTC)<input v-model="maintenance.ends_at" type="datetime-local" required/></label><label>Причина<input v-model="maintenance.reason" required/></label><button :disabled="maintenance.processing">Сохранить интервал</button><p class="error" v-for="error in maintenance.errors" :key="error">{{error}}</p></form>
</Shell></template>
