<script setup lang="ts">
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';import Shell from '../Layouts/Shell.vue';
defineProps<{clubs:{id:number;name:string}[];published:{app_id:number;build_id:string|null;source:string;source_status:string;checked_at:string|null;candidate:string|null}[];local:{data:{id:number;equipment_id:number;name:string;product:string;value:string;observed_at:string}[];next_page_url:string|null;prev_page_url:string|null};checks:{id:number;equipment_id:number;product:string;checked_value:string;result:string}[];subscriptions:{club_id:number;app_id:number}[]}>();
const page=usePage<{auth:{user:{role:string}}}>();const sub=useForm({club_id:'',app_id:730});const check=useForm({equipment_id:'',product:'730',checked_value:'',result:''});const name=(id:string|number)=>String(id)==='730'?'CS2':String(id)==='570'?'Dota 2':'Файл FACEIT';
</script>
<template><Head title="Обновления"/><Shell><h1>Обновления игр и FACEIT</h1><section class="panel"><h2>Опубликованные сборки</h2><p>Сторонний источник steamcmd.net, ветка public. Изменение build ID может быть откатом. Первая версия сохраняется без уведомления, последующие изменения подтверждаются двумя проверками.</p><p v-if="!published.length">Нет проверок. Добавьте подписку клуба.</p><table><tbody><tr v-for="p in published" :key="p.app_id"><td>{{name(p.app_id)}}</td><td>{{p.build_id||'Нет данных'}}</td><td>{{p.source_status}}</td><td>{{p.checked_at||'Не проверялось'}}</td></tr></tbody></table></section>
<form v-if="['owner','lead'].includes(page.props.auth.user.role)" class="panel form-grid" @submit.prevent="sub.post('/updates/subscribe')"><label>Клуб<select v-model="sub.club_id" required><option v-for="c in clubs" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>Игра<select v-model="sub.app_id"><option :value="730">CS2</option><option :value="570">Dota 2</option></select></label><button :disabled="sub.processing">Подписать клуб</button><p v-for="error in sub.errors" :key="error" class="error">{{error}}</p></form>
<section class="panel"><h2>Локальные версии</h2><p>Данные от агента не подтверждают работоспособность игры. Для FACEIT отслеживается хеш выбранного файла; это не подтверждённый релиз античита. Если manifest отсутствует в установке iCafeCloud, версия недоступна.</p><table><tbody><tr v-for="v in local.data" :key="v.id"><td>#{{v.equipment_id}} {{v.name}}</td><td>{{name(v.product)}}</td><td class="prewrap">{{v.value}}</td></tr></tbody></table><Link v-if="local.prev_page_url" :href="local.prev_page_url">Назад</Link><Link v-if="local.next_page_url" :href="local.next_page_url">Далее</Link></section>
<form v-if="page.props.auth.user.role!=='representative'" class="panel form-grid" @submit.prevent="check.post('/updates/verify')"><h2>Проверка специалистом</h2><label>ID оборудования<input v-model="check.equipment_id" type="number" required/></label><label>Продукт<select v-model="check.product"><option value="730">CS2</option><option value="570">Dota 2</option><option value="faceit_file">FACEIT (контролируемый файл)</option></select></label><label>Проверенный build ID / хеш<input v-model="check.checked_value" required/></label><label>Результат запуска<textarea v-model="check.result" required minlength="5"/></label><button :disabled="check.processing">Зафиксировать проверку</button><p class="error" v-for="error in check.errors" :key="error">{{error}}</p></form>
<section class="panel"><h2>Подтверждения работоспособности</h2><p v-if="!checks.length">Проверок специалистом пока нет.</p><p v-for="c in checks" :key="c.id">ПК #{{c.equipment_id}} · {{name(c.product)}} · {{c.checked_value}} — {{c.result}}</p></section></Shell></template>
