<script setup lang="ts">
import { useForm, Link } from '@inertiajs/vue3';
const props=defineProps<{inspection:{id:number;status:string;equipment:{name:string};approved_at:string|null;findings:string|null;ticket_id:number|null;work_done:string|null;verification:string|null;skip_reason:string|null;rescheduled_date:string|null};items:string[];canEdit:boolean;canApprove:boolean}>();
const labels:Record<string,string>={dust:'Пыль и фильтры',case:'Корпус и крепления',fans:'Вентиляторы',cables:'Кабели и разъёмы',monitor:'Монитор',peripherals:'Клавиатура, мышь, гарнитура',usb_audio:'USB и аудио',temperatures:'Температуры и условия измерения',damage:'Повреждения',work:'Выполненные работы',boot_game:'Загрузка и запуск игры'};
const form=useForm({status:'completed',checklist:Object.fromEntries(props.items.map(i=>[i,'unchecked'])),work_type:'inspection',findings:'',work_done:'',verification:'',skip_reason:'',rescheduled_date:''});
const approval=useForm({approval:''});
const upload=useForm({type:'inspection',id:props.inspection.id,stage:'before',file:null as File|null});
</script>
<template><section class="panel"><h2>{{inspection.equipment.name}} · {{ {pending:'Ожидает осмотра',completed:'Осмотрен',skipped:'Пропущен'}[inspection.status] }}</h2>
<form v-if="canApprove&&inspection.status==='pending'" class="toolbar" @submit.prevent="approval.post('/inspections/'+inspection.id+'/approve')"><label>Согласованный объём дополнительных работ<input v-model="approval.approval" minlength="5" required/></label><button :disabled="approval.processing">Согласовать</button></form><p v-if="inspection.approved_at" class="success">Согласование зафиксировано</p>
<form v-if="canEdit&&inspection.status==='pending'" class="form-grid" @submit.prevent="form.post('/inspections/'+inspection.id)"><label>Результат<select v-model="form.status"><option value="completed">Осмотрен</option><option value="skipped">Пропущен</option></select></label>
<template v-if="form.status==='completed'"><label v-for="item in items" :key="item">{{labels[item]}}<select v-model="form.checklist[item]"><option value="ok">Исправно</option><option value="problem">Проблема</option><option value="unchecked">Не проверено</option><option value="na">Неприменимо</option></select></label><label>Вид работы<select v-model="form.work_type"><option value="inspection">Осмотр</option><option value="cleaning">Стандартная чистка</option><option value="disassembly">Сложная разборка</option><option value="replacement">Замена комплектующих</option></select></label><label>Найденные проблемы / температуры и условия<textarea v-model="form.findings"/></label><label>Выполненные действия<textarea v-model="form.work_done" required/></label><label>Проверка загрузки и игры<textarea v-model="form.verification" required/></label></template>
<template v-else><label>Причина пропуска<textarea v-model="form.skip_reason" required/></label><label>Новая дата<input v-model="form.rescheduled_date" type="date" required/></label></template><p class="error" v-for="error in form.errors" :key="error">{{error}}</p><button :disabled="form.processing">Сохранить результат ПК</button></form>
<div v-if="inspection.status!=='pending'"><p>{{inspection.work_done||inspection.skip_reason}}</p><p>{{inspection.verification}}</p><p v-if="inspection.rescheduled_date">Новый срок: {{inspection.rescheduled_date}}</p><p>{{inspection.findings}}</p><Link v-if="canEdit&&inspection.findings" :href="'/inspections/'+inspection.id+'/ticket'" method="post" as="button">{{inspection.ticket_id?'Открыть заявку':'Создать заявку из проблемы'}}</Link></div>
<form v-if="canEdit" class="toolbar" @submit.prevent="upload.post('/attachments',{forceFormData:true})"><label>Фотографии / документ<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" @change="upload.file=($event.target as HTMLInputElement).files?.[0]??null" required/></label><select v-model="upload.stage" aria-label="Этап фото"><option value="before">До</option><option value="after">После</option></select><button :disabled="upload.processing">Прикрепить</button><p v-for="error in upload.errors" :key="error" class="error">{{error}}</p></form>
</section></template>
