<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,watch} from 'vue';
import {Link,useForm} from '@inertiajs/vue3';
type Pc={id:number;name:string;zone:string|null;online:boolean|null;cpu_temp:number|null;gpu_temp:number|null;observed_at:string|null;severity:string;imported:boolean};
type Snapshot={pcs:Pc[];error:string|null;updated_at:string;connection_updated_at:string|null;template:{warning:number;critical:number;hold_seconds:number}};
const props=defineProps<{clubs:{id:number;name:string;icafe_license?:number|null}[];canManage:boolean}>();
const club=ref(props.clubs.find(c=>c.icafe_license)?.id??props.clubs[0]?.id??0),data=ref<Snapshot|null>(null),error=ref(''),busy=ref(false),search=ref(''),filter=ref('all');
const importing=useForm({import:''}),template=useForm({warning:50,critical:79,hold_seconds:0});
const labels:Record<string,string>={normal:'Норма',warning:'Повышенная',critical:'Перегрев',unknown:'Нет данных',offline:'Офлайн'};
const shown=computed(()=>data.value?.pcs.filter(p=>(filter.value==='all'||p.severity===filter.value)&&(p.name+' '+(p.zone??'')).toLowerCase().includes(search.value.toLowerCase()))??[]);
const count=(kind:string)=>data.value?.pcs.filter(p=>p.severity===kind).length??0;
const degrees=(n:number|null)=>n===null?'Нет данных':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(n)+' °C';
const updated=computed(()=>data.value?.connection_updated_at?new Date(data.value.connection_updated_at).toLocaleTimeString('ru-RU'):'нет данных');
let timer:ReturnType<typeof setTimeout>|undefined,controller:AbortController|undefined,initialized=false;
async function refresh(){if(!club.value||busy.value||document.hidden)return;const c=new AbortController();controller=c;busy.value=true;error.value='';const timeout=setTimeout(()=>c.abort('timeout'),45000);
 try{const r=await fetch('/monitoring/clubs/'+club.value,{signal:c.signal,headers:{Accept:'application/json'}});if(r.status===401||r.redirected){window.location.assign('/login');return;}if(!r.ok)throw new Error('Не удалось обновить мониторинг');const result=await r.json();if(c.signal.aborted)return;data.value=result;if(!initialized){Object.assign(template,result.template);initialized=true;}}
 catch(e){if(!c.signal.aborted||c.signal.reason==='timeout')error.value='Нет связи с сервером. Показания на экране могут быть устаревшими.';}
 finally{clearTimeout(timeout);if(controller===c){busy.value=false;clearTimeout(timer);timer=setTimeout(refresh,15000);}}
}
watch(club,()=>{controller?.abort();clearTimeout(timer);busy.value=false;data.value=null;initialized=false;filter.value='all';void refresh();});
function visible(){if(!document.hidden)void refresh();}
onMounted(()=>{void refresh();document.addEventListener('visibilitychange',visible);});onUnmounted(()=>{controller?.abort();controller=undefined;clearTimeout(timer);document.removeEventListener('visibilitychange',visible);});
</script>
<template>
 <section class="panel pc-board">
  <div class="toolbar"><div><p class="eyebrow">LIVE / СОСТОЯНИЕ КЛУБА</p><h2>Температуры компьютеров</h2></div><label>Клуб мониторинга<select v-model="club"><option v-for="c in clubs" :key="c.id" :value="c.id">{{c.name}}</option></select></label></div>
  <p class="monitor-note">CPU / GPU · автообновление каждые 15 секунд · онлайн-статусы: {{updated}}. Температуры поступают от Windows-агента, не из iCafeCloud.</p>
  <div class="monitor-tools"><button v-if="canManage" :disabled="!club||importing.processing" @click="importing.post('/monitoring/clubs/'+club+'/import',{preserveScroll:true,onSuccess:()=>refresh()})">{{importing.processing?'Импортируем…':'Импортировать ПК из iCafeCloud'}}</button><button class="secondary" :disabled="busy||!club" @click="refresh">{{busy?'Обновляем…':'Обновить'}}</button></div>
  <p v-for="e in importing.errors" :key="e" class="error" role="alert">{{e}}</p><p v-if="error||data?.error" class="monitor-warning" role="alert">{{error||data?.error}}</p>
  <div class="pc-legend"><span class="normal">Норма &lt; {{data?.template.warning??50}} °C</span><span class="warning">{{data?.template.warning??50}}–{{data?.template.critical??79}} °C</span><span class="critical">Перегрев &gt; {{data?.template.critical??79}} °C</span><span>Серый: офлайн / нет датчиков</span></div>
  <p class="monitor-note">Цвет по худшему показателю CPU/GPU. Если один датчик отсутствует, безопасный статус не подтверждается. Показания старше 3 минут скрываются.</p>
  <div v-if="data" class="monitor-summary"><b>Всего {{data.pcs.length}}</b><span>Онлайн {{data.pcs.filter(p=>p.online===true).length}}</span><span>Офлайн {{count('offline')}}</span><span>Перегрев {{count('critical')}}</span><span>Повышенная {{count('warning')}}</span><span>Нет данных {{count('unknown')}}</span></div>
  <div class="monitor-filters"><label>Поиск ПК / зоны<input v-model="search" placeholder="Например, 001"/></label><label>Показать<select v-model="filter"><option value="all">Все компьютеры</option><option v-for="(label,key) in labels" :key="key" :value="key">{{label}}</option></select></label></div>
  <div v-if="!shown.length" class="empty">{{busy?'Получаем данные…':data?.pcs.length?'По фильтру компьютеров нет.':'ПК ещё не импортированы. Администратор может импортировать список из iCafeCloud.'}}</div>
  <div class="pc-tiles"><Link v-for="pc in shown" :key="pc.id" :href="'/equipment/'+pc.id" :class="['pc-tile',error?'unknown':pc.severity]" :aria-label="pc.name+': '+(error?'Нет свежих данных':labels[pc.severity])">
   <div class="pc-top"><strong>{{pc.name}}</strong><span>{{pc.online===true?'Онлайн':pc.online===false?'Офлайн':'Связь неизвестна'}}</span></div>
   <svg class="pc-symbol" viewBox="0 0 160 108" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="12" y="14" width="102" height="66" rx="6" fill="currentColor" fill-opacity=".06"/><path d="M12 65h102M54 81v12m18-12v12M42 94h42"/><path d="M27 44h17l6-13 11 25 9-17 6 5h22" opacity=".8"/><rect x="124" y="9" width="25" height="85" rx="5" fill="currentColor" fill-opacity=".06"/><circle cx="136.5" cy="36" r="7"/><circle cx="136.5" cy="60" r="7"/><path d="M132 81h9"/><circle cx="136.5" cy="19" r="1" fill="currentColor"/></svg>
   <div class="temp-readings"><div><small>CPU</small><b>{{error?'Нет данных':degrees(pc.cpu_temp)}}</b></div><div><small>GPU</small><b>{{error?'Нет данных':degrees(pc.gpu_temp)}}</b></div></div>
   <div class="pc-bottom"><span>{{error?'Нет свежих данных':labels[pc.severity]}}</span><small>#{{pc.id}} · {{pc.zone||'Без зоны'}}</small></div>
  </Link></div>
  <details v-if="canManage&&club" class="template-settings"><summary>Единый шаблон триггеров CPU/GPU для всех ПК клуба</summary><form class="form-grid" @submit.prevent="template.post('/monitoring/clubs/'+club+'/template',{preserveScroll:true,onSuccess:()=>{initialized=false;void refresh();}})"><label>Жёлтый от, °C<input v-model="template.warning" type="number" step="0.01" min="1" max="149" required/></label><label>Красный выше, °C<input v-model="template.critical" type="number" step="0.01" min="1" max="150" required/></label><label>Выдержка тревоги, секунд<input v-model="template.hold_seconds" type="number" min="0" max="3600" required/></label><button :disabled="template.processing">Сохранить шаблон</button><p v-for="e in template.errors" :key="e" class="error">{{e}}</p></form><p class="monitor-note">Шаблон применяется к CPU и GPU всех текущих и будущих ПК клуба. Цвет меняется сразу; выдержка влияет только на создание тревоги. Восстановление — ниже жёлтого порога.</p></details>
 </section>
</template>
<style scoped>
.pc-board{--pc-green:#16805c;--pc-yellow:#946100;--pc-red:#c33445;--pc-gray:#697586}.monitor-tools,.monitor-summary,.pc-legend{display:flex;gap:12px;flex-wrap:wrap;margin:18px 0}.monitor-note{font-size:12px;color:var(--muted);max-width:900px}.pc-legend span{font-size:12px;padding:7px 10px;border:1px solid currentColor;border-radius:4px}.normal{color:var(--pc-green)}.warning{color:var(--pc-yellow)}.critical{color:var(--pc-red)}.unknown,.offline{color:var(--pc-gray)}.monitor-summary{border-block:1px solid var(--border);padding:14px 0;font-variant-numeric:tabular-nums}.monitor-filters{display:grid;grid-template-columns:2fr 1fr;gap:14px;margin-bottom:22px}.pc-tiles{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:14px}.pc-tile{display:block;border:1px solid var(--border);border-top:3px solid currentColor;border-radius:8px;padding:16px;transition:background .15s}.pc-tile:hover{background:rgba(127,127,127,.07);color:inherit}.pc-top{display:flex;gap:8px;justify-content:space-between;align-items:center}.pc-top strong{font-size:20px;overflow-wrap:anywhere}.pc-top span{font-size:10px;text-align:right}.pc-symbol{width:100%;height:100px;margin:12px 0}.temp-readings{display:grid;grid-template-columns:1fr 1fr;gap:12px}.temp-readings div{display:grid;gap:4px}.temp-readings small{font-size:10px;letter-spacing:1px}.temp-readings b{font-size:16px;font-variant-numeric:tabular-nums}.pc-bottom{border-top:1px solid var(--border);margin-top:14px;padding-top:10px;display:grid;gap:5px;font-size:12px}.pc-bottom small{color:var(--muted)}.template-settings{border-top:1px solid var(--border);padding-top:20px;margin-top:28px}.template-settings summary{cursor:pointer;font-weight:600;padding:10px 0}.template-settings form{margin-top:18px}.monitor-warning{border-left:3px solid #b78500;padding:10px 16px;background:rgba(200,150,0,.1)}:global([data-theme=dark] .pc-board){--pc-green:#76dba6;--pc-yellow:#ffcf66;--pc-red:#ff8790;--pc-gray:#acb4c4}@media(max-width:600px){.monitor-filters{grid-template-columns:1fr}.pc-tiles{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.pc-tile{padding:10px}.pc-top{flex-direction:column;align-items:flex-start}.pc-symbol{height:80px}.temp-readings{grid-template-columns:1fr}.pc-top strong{font-size:18px}}
</style>
